name: Test
on: [pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq make cmake gcc g++
      - name: build
        shell: bash
        run: |
          export LD_LIBRARY_PATH=.:$(cat /etc/ld.so.conf.d/* | grep -vF "#" | tr "\\n" ":" | sed -e "s/:$//g")
          cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_SANITIZERS=On && make all -j$(nproc)
      - name: test
        shell: bash
        run: |
          export LD_LIBRARY_PATH=.:$(cat /etc/ld.so.conf.d/* | grep -vF "#" | tr "\\n" ":" | sed -e "s/:$//g")
          #TODO: run statsd to collect these test metrics
          ./testStatsdClient
          #TODO: validate test metrics received
